[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "https://loan-calculator-aleksey-vl-ivanov.netlify.app/*"
  to = "https://loan-calculator.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://loan-calculator-aleksey-vl-ivanov.netlify.app/*"
  to = "https://loan-calculator.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://loan-calculator.aleksey-vl-ivanov.com/*"
  to = "https://loan-calculator.aleksey-vl-ivanov.com/:splat"
  status = 301
  force = true
